// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-api/internal/handler"
	"go-api/internal/logic"
	"go-api/internal/mapper"
	"go-api/router"
)

// Injectors from wire.go:

// 初始化服务器
func initServer() (*Server, func(), error) {
	helloMapper := mapper.NewHelloMapper()
	helloLogic := logic.NewHelloLogic(helloMapper)
	helloHandler := handler.NewHelloHandler(helloLogic)
	routerRouter := router.New(helloHandler)
	mainServer := New(routerRouter)
	return mainServer, func() {
	}, nil
}
