base:
  is_dev : false
out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language :  # 语言(English,中 文)
db_tag : gorm # 数据库标签名(gorm,db)
simple : false # 简单输出(默认只输出gorm主键和字段标签)
user_gorm_model : false # model是否使用gorm.Model
is_db_tag : false # 是否输出 数据库标签(gorm,db)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : false # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: false # web标记是否隐藏主键
is_foreign_key : false # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : true # 是否直接生成表名
is_column_name : true # 是否直接生成列名
is_null_to_point : false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
table_prefix : "" # 表前缀, 如果有则使用, 没有留空
table_names: ""
is_out_page: false # 是否输出分页函数

db_info:
  host: 127.0.0.1 # type=1的时候，host为yml文件全路径
  port: 3306
  username: root
  password: june0719.master
  database: api
  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
self_type_define: # 自定义数据类型映射
  datetime: time.Time
  time: time.Time
  date: time.Time
  decimal: string
  ^(int)[(]\d+[)]: int
out_file_name: "api" # 自定义生成文件名
web_tag_type: 1 # json tag类型 0: 小驼峰 1: 下划线